
CREATE TABLE IF NOT EXISTS mpas (
  mpa_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL,
  login varchar(255) NOT NULL,
  name varchar(255) NOT NULL,
  birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
  film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  description varchar(200) NOT NULL,
  releaseDate date NOT NULL,
  duration int NOT NULL,
  mpa_id int NOT NULL REFERENCES mpas (mpa_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS genres (
  genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS film_to_genres (
  film_id BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
  genre_id int REFERENCES genres (genre_id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS likes (
  film_id BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
  user_id bigint REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friendships (
  user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
  friend_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
  status boolean NOT NULL
);
